language: node_js
node_js:
  - 12

# SCRIPTS RO RUN
script:
  - echo '*********Build Starts*********'
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Running test'
  - npm test

# ONLY APPLY TO THIS BRANCH
branches:
  only:
    - main

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
