language: node_js
node_js:
  - 12
script:
  - echo '*********Build Starts*********'
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Running test'
  - npm test
branches:
  only:
    - main
